server:
  port: 8086

spring:
  application:
    name: social-service
  datasource:
    url: jdbc:sqlserver://${DB_HOST:sqlserver}:${DB_PORT:1433};databaseName=chaghaf_social;encrypt=true;trustServerCertificate=true
    username: ${DB_USER:sa}
    password: ${DB_PASS:Chaghaf@2025!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASS:chaghaf2025}@discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    ma.chaghaf.social: DEBUG
