server:
  port: 8761

spring:
  application:
    name: discovery-service
  security:
    user:
      name: ${EUREKA_USER:admin}
      password: ${EUREKA_PASS:chaghaf2025}

eureka:
  instance:
    hostname: discovery-service
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASS:chaghaf2025}@localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    renewal-percent-threshold: 0.85

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
